// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIaInHNMpqgDU4qcCFkmL0Oy1HYIrpuAY',
    appId: '1:180967353053:web:c1f0f1c29c2e39b0e18934',
    messagingSenderId: '180967353053',
    projectId: 'sparkchat-9e8a0',
    authDomain: 'sparkchat-9e8a0.firebaseapp.com',
    storageBucket: 'sparkchat-9e8a0.firebasestorage.app',
    measurementId: 'G-EJ2XB41G9V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBbGXOVHL-54RAJPpbh-GqExK74DDI1Sw',
    appId: '1:180967353053:android:5cebc3e84a0fac44e18934',
    messagingSenderId: '180967353053',
    projectId: 'sparkchat-9e8a0',
    storageBucket: 'sparkchat-9e8a0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQ4RGettL1TUSmn7VIHRM7QRLlWzL5l0Y',
    appId: '1:180967353053:ios:77dcfcd96336a3cfe18934',
    messagingSenderId: '180967353053',
    projectId: 'sparkchat-9e8a0',
    storageBucket: 'sparkchat-9e8a0.firebasestorage.app',
    iosBundleId: 'com.example.sparkChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQ4RGettL1TUSmn7VIHRM7QRLlWzL5l0Y',
    appId: '1:180967353053:ios:77dcfcd96336a3cfe18934',
    messagingSenderId: '180967353053',
    projectId: 'sparkchat-9e8a0',
    storageBucket: 'sparkchat-9e8a0.firebasestorage.app',
    iosBundleId: 'com.example.sparkChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIaInHNMpqgDU4qcCFkmL0Oy1HYIrpuAY',
    appId: '1:180967353053:web:66fb47bb5f8dcfd6e18934',
    messagingSenderId: '180967353053',
    projectId: 'sparkchat-9e8a0',
    authDomain: 'sparkchat-9e8a0.firebaseapp.com',
    storageBucket: 'sparkchat-9e8a0.firebasestorage.app',
    measurementId: 'G-ZJSJ843XVC',
  );
}
